### ISSUE TITLE
CS1061

### ISSUE THREAD

**Issue by JoseGoncalves3** [MicrosoftDocs/powerbi-docs.pt-pt#3]
Using this code, i am having a error, a CS1061, it says "'AuthenticationContext' does not contain a definition for 'AcquireToken' and no accessible 'AcquireToken' accepting a first argument of type 'AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)", can someone help?

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Obter um token de acesso de autenticação - Power BI](https://docs.microsoft.com/pt-pt/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-pt/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by CeciAc** [comment]
Hello, @JoseGoncalves3 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
